packages:
  - demo/*

catalog:
  '@babel/core': ^8.0.0-rc.5
  '@biomejs/biome': ^2.4.14
  '@expo-google-fonts/jetbrains-mono': ^0.4.1
  '@mdn/browser-compat-data': ^8.0.0
  '@resvg/resvg-js': ^2.6.2
  '@tsconfig/bases': ^1.0.23
  '@types/node': ^25.6.0
  globals: ^17.6.0
  ignore: ^7.0.5
  p-limit: ^7.3.0
  satori: ^0.26.0
  shiki: ^4.0.2
  svelte: ^5.55.9
  tsdown: ^0.22.0
  typescript: ^6.0.3
  unplugin: ^3.0.0
  vitest: ^4.1.5

catalogMode: strict
